-- ============================================================================
-- 02_RAW_TABLES.SQL — Raw tables for E-Commerce Marketplace Analytics
-- ============================================================================
USE DATABASE ECOMMERCE_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.ORDERS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SELLERS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.BUYERS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CAMPAIGNS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SELLER_DOCS (
  ID VARCHAR DEFAULT UUID_STRING(),
  DATA VARIANT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

