-- ============================================================================
-- 02_RAW_TABLES.SQL — Raw tables for E-Commerce Marketplace Analytics
-- Indonesian e-commerce marketplace: Tokopedia/Shopee/Bukalapak style
-- ============================================================================
USE DATABASE DIGITAL_ECOMMERCE;
USE SCHEMA RAW;

-- 50,000 marketplace sellers across Java, Sumatra, Kalimantan
CREATE OR REPLACE TABLE RAW.SELLERS (
  SELLER_ID VARCHAR(20) NOT NULL, SELLER_NAME VARCHAR(200), CITY VARCHAR(50), PROVINCE VARCHAR(50), CATEGORY VARCHAR(50), RATING FLOAT, TOTAL_PRODUCTS INT, JOIN_DATE DATE, IS_OFFICIAL_STORE BOOLEAN, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 2M orders over 12 months
CREATE OR REPLACE TABLE RAW.ORDERS (
  ORDER_ID VARCHAR(30) NOT NULL, SELLER_ID VARCHAR(20), BUYER_PROVINCE VARCHAR(50), ORDER_DATE TIMESTAMP, PRODUCT_CATEGORY VARCHAR(50), QUANTITY INT, UNIT_PRICE FLOAT, TOTAL_AMOUNT FLOAT, PAYMENT_METHOD VARCHAR(30), SHIPPING_PROVIDER VARCHAR(30), STATUS VARCHAR(20), DELIVERED_DATE TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 500K product listings
CREATE OR REPLACE TABLE RAW.PRODUCTS (
  PRODUCT_ID VARCHAR(30) NOT NULL, SELLER_ID VARCHAR(20), PRODUCT_NAME VARCHAR(300), CATEGORY VARCHAR(50), SUBCATEGORY VARCHAR(50), PRICE FLOAT, STOCK_QTY INT, RATING FLOAT, REVIEW_COUNT INT, IS_PROMOTED BOOLEAN, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Customer reviews with AI sentiment scores
CREATE OR REPLACE TABLE RAW.REVIEWS (
  REVIEW_ID VARCHAR(30) NOT NULL, ORDER_ID VARCHAR(30), PRODUCT_ID VARCHAR(30), RATING INT, REVIEW_TEXT VARCHAR(2000), SENTIMENT_SCORE FLOAT, REVIEW_DATE TIMESTAMP, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
