-- ============================================================================
-- 04_DYNAMIC_TABLES.SQL — Curated layer for E-Commerce Marketplace Analytics
-- Real aggregation logic producing analytics-ready tables
-- ============================================================================
USE DATABASE DIGITAL_ECOMMERCE;
USE SCHEMA CURATED;

CREATE OR REPLACE DYNAMIC TABLE CURATED.SELLER_PERFORMANCE
  TARGET_LAG = '5 minutes'
  WAREHOUSE = ECOMMERCE_WH
AS
SELECT
  s.SELLER_ID, s.SELLER_NAME, s.CITY, s.PROVINCE, s.CATEGORY, s.IS_OFFICIAL_STORE,
  COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
  ROUND(SUM(o.TOTAL_AMOUNT), 0) AS TOTAL_GMV,
  ROUND(AVG(o.TOTAL_AMOUNT), 0) AS AVG_ORDER_VALUE,
  ROUND(SUM(CASE WHEN o.STATUS = 'DELIVERED' THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 1) AS FULFILLMENT_RATE,
  ROUND(AVG(DATEDIFF('hour', o.ORDER_DATE, o.DELIVERED_DATE)), 1) AS AVG_DELIVERY_HOURS,
  ROUND(AVG(r.RATING), 2) AS AVG_REVIEW_RATING,
  COUNT(DISTINCT CASE WHEN o.ORDER_DATE >= DATEADD('day', -30, CURRENT_DATE()) THEN o.ORDER_ID END) AS ORDERS_LAST_30D
FROM RAW.SELLERS s
LEFT JOIN RAW.ORDERS o ON s.SELLER_ID = o.SELLER_ID
LEFT JOIN RAW.REVIEWS r ON o.ORDER_ID = r.ORDER_ID
GROUP BY 1,2,3,4,5,6;

CREATE OR REPLACE DYNAMIC TABLE CURATED.CATEGORY_TRENDS
  TARGET_LAG = '5 minutes'
  WAREHOUSE = ECOMMERCE_WH
AS
SELECT
  o.PRODUCT_CATEGORY AS CATEGORY,
  DATE_TRUNC('week', o.ORDER_DATE) AS WEEK_START,
  COUNT(DISTINCT o.ORDER_ID) AS ORDER_COUNT,
  COUNT(DISTINCT o.SELLER_ID) AS ACTIVE_SELLERS,
  ROUND(SUM(o.TOTAL_AMOUNT) / 1000000, 2) AS GMV_MILLIONS,
  ROUND(AVG(o.TOTAL_AMOUNT), 0) AS AVG_BASKET_SIZE,
  ROUND(AVG(r.SENTIMENT_SCORE), 3) AS AVG_SENTIMENT,
  ROUND(SUM(CASE WHEN o.STATUS = 'RETURNED' THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS RETURN_RATE
FROM RAW.ORDERS o
LEFT JOIN RAW.REVIEWS r ON o.ORDER_ID = r.ORDER_ID
GROUP BY 1, 2;

CREATE OR REPLACE DYNAMIC TABLE CURATED.REGIONAL_DEMAND
  TARGET_LAG = '5 minutes'
  WAREHOUSE = ECOMMERCE_WH
AS
WITH daily_orders AS (
  SELECT
    BUYER_PROVINCE,
    DATE_TRUNC('day', ORDER_DATE) AS ORDER_DAY,
    COUNT(*) AS DAILY_ORDERS,
    SUM(TOTAL_AMOUNT) AS DAILY_GMV
  FROM RAW.ORDERS
  WHERE STATUS != 'CANCELLED'
  GROUP BY 1, 2
)
SELECT
  BUYER_PROVINCE,
  ORDER_DAY,
  DAILY_ORDERS,
  ROUND(DAILY_GMV, 0) AS DAILY_GMV,
  ROUND(AVG(DAILY_ORDERS) OVER (PARTITION BY BUYER_PROVINCE ORDER BY ORDER_DAY ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 0) AS MA_7D_ORDERS,
  ROUND(SUM(DAILY_GMV) OVER (PARTITION BY BUYER_PROVINCE ORDER BY ORDER_DAY ROWS BETWEEN 29 PRECEDING AND CURRENT ROW), 0) AS ROLLING_30D_GMV
FROM daily_orders;
