-- Generated from generator/demo_specs/aws-indonesia-digital-economy-ecommerce.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-digital-economy-ecommerce
-- This is the schema that is actually deployed for ID_DIGITAL_ECONOMY_ECOMMERCE.

-- Alerts fire on the bottom tail of Order Fulfillment
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ORDER_FULFILLMENT) AS T
  FROM RAW.ORDERS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ORDER_FULFILLMENT <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ORDER_FULFILLMENT), 2) AS AVG_ORDER_FULFILLMENT,
  ROUND(AVG(f.KPI_AVG_ORDER_VALUE), 2) AS AVG_ORDER_VALUE,
  ROUND(AVG(f.KPI_REPEAT_PURCHASE), 2) AS AVG_REPEAT_PURCHASE,
  ROUND(AVG(f.KPI_CART_ABANDONMENT), 2) AS AVG_CART_ABANDONMENT,
  ROUND(AVG(f.KPI_FRAUD_RATE), 2) AS AVG_FRAUD_RATE
FROM RAW.ORDERS f
JOIN RAW.SELLER_DOCS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ORDER_FULFILLMENT), 2) AS AVG_ORDER_FULFILLMENT,
  ROUND(AVG(f.KPI_AVG_ORDER_VALUE), 2) AS AVG_ORDER_VALUE,
  ROUND(AVG(f.KPI_REPEAT_PURCHASE), 2) AS AVG_REPEAT_PURCHASE,
  ROUND(AVG(f.KPI_CART_ABANDONMENT), 2) AS AVG_CART_ABANDONMENT,
  ROUND(AVG(f.KPI_FRAUD_RATE), 2) AS AVG_FRAUD_RATE
FROM RAW.ORDERS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_FRAUD_RATE) AS KPI_FRAUD_RATE, AVG(KPI_ORDER_FULFILLMENT) AS KPI_ORDER_FULFILLMENT, AVG(KPI_AVG_ORDER_VALUE) AS KPI_AVG_ORDER_VALUE, AVG(KPI_REPEAT_PURCHASE) AS KPI_REPEAT_PURCHASE, AVG(KPI_CART_ABANDONMENT) AS KPI_CART_ABANDONMENT FROM RAW.ORDERS),
     en AS (SELECT SUM(KPI_GMV_MTD) AS KPI_GMV_MTD, SUM(KPI_ACTIVE_MERCHANTS) AS KPI_ACTIVE_MERCHANTS FROM RAW.SELLER_DOCS)
  SELECT 1 AS SORT_ORDER, 'GMV (MTD)' AS TITLE, KPI_GMV_MTD AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_GMV_MTD) / 1000000000000), 1) AS DECIMAL(38,1))) || 'T' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Active Merchants' AS TITLE, KPI_ACTIVE_MERCHANTS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ACTIVE_MERCHANTS) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Fraud Rate' AS TITLE, KPI_FRAUD_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FRAUD_RATE), 2) AS DECIMAL(38,2))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Order Fulfillment' AS TITLE, KPI_ORDER_FULFILLMENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ORDER_FULFILLMENT), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Order Value' AS TITLE, KPI_AVG_ORDER_VALUE AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_AVG_ORDER_VALUE) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Repeat Purchase' AS TITLE, KPI_REPEAT_PURCHASE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_REPEAT_PURCHASE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Cart Abandonment' AS TITLE, KPI_CART_ABANDONMENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CART_ABANDONMENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
