-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT seller.ID AS ENTITY_ID, seller.NAME AS ENTITY_NAME,
       seller.REGION, seller.CATEGORY, seller.RISK_TIER, seller.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.ORDER_COUNT) AS ORDER_COUNT,
       SUM(observation.GMV_IDR) AS GMV_IDR,
       SUM(observation.ISSUE_COUNT) AS ISSUE_COUNT,
       SUM(observation.CANCELLED_COUNT) AS CANCELLED_COUNT,
       SUM(observation.LATE_DELIVERY) AS LATE_DELIVERY_COUNT,
       SUM(observation.STOCK_SYNC_DUE) AS STOCK_SYNC_DUE,
       SUM(observation.STOCK_SYNC_DONE) AS STOCK_SYNC_DONE,
       100.0 * (SUM(observation.ORDER_COUNT) - SUM(observation.ISSUE_COUNT)) / NULLIF(SUM(observation.ORDER_COUNT), 0) AS CLEAN_ORDER_PCT,
       100.0 * SUM(observation.CANCELLED_COUNT) / NULLIF(SUM(observation.ISSUE_COUNT), 0) AS ISSUE_CANCEL_PCT,
       100.0 * SUM(observation.STOCK_SYNC_DONE) / NULLIF(SUM(observation.STOCK_SYNC_DUE), 0) AS STOCK_SYNC_PCT,
       AVG(observation.RETURN_RATE_PCT) AS AVG_RETURN_RATE_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.SELLER_DAILY observation
JOIN RAW.SELLERS seller ON seller.ID = observation.ENTITY_ID
GROUP BY seller.ID, seller.NAME, seller.REGION, seller.CATEGORY, seller.RISK_TIER, seller.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(ORDER_COUNT) AS ORDER_COUNT, SUM(GMV_IDR) AS GMV_IDR,
       SUM(ISSUE_COUNT) AS ISSUE_COUNT, SUM(CANCELLED_COUNT) AS CANCELLED_COUNT,
       100.0 * SUM(CANCELLED_COUNT) / NULLIF(SUM(ISSUE_COUNT), 0) AS ISSUE_CANCEL_PCT
FROM RAW.SELLER_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.ISSUE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT ISSUE_TYPE, SUM(ISSUE_COUNT) AS ISSUE_COUNT,
       SUM(CANCELLED_COUNT) AS CANCELLED_COUNT,
       SUM(LATE_DELIVERY) AS LATE_DELIVERY_COUNT,
       SUM(GMV_IDR) AS EXPOSED_GMV_IDR,
       100.0 * SUM(CANCELLED_COUNT) / NULLIF(SUM(ISSUE_COUNT), 0) AS ISSUE_CANCEL_PCT
FROM RAW.SELLER_DAILY
WHERE ISSUE_COUNT > 0
GROUP BY ISSUE_TYPE;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(ORDER_COUNT) AS ORDERS, SUM(ISSUE_COUNT) AS ISSUES,
         SUM(CANCELLED_COUNT) AS CANCELLED, SUM(LATE_DELIVERY) AS BREACHES, SUM(GMV_IDR) AS GMV_IDR,
         SUM(STOCK_SYNC_DUE) AS STOCK_SYNC_DUE, SUM(STOCK_SYNC_DONE) AS STOCK_SYNC_DONE,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.SELLER_DAILY
), book AS (SELECT COUNT(*) AS SELLER_COUNT FROM RAW.SELLERS),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.COMPLIANCE_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Clean Order Rate' AS TITLE,
         100.0 * (ORDERS - ISSUES) / NULLIF(ORDERS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Order Issues Raised', ISSUES, '' FROM observations
  UNION ALL SELECT 3, 'Cancelled Orders', CANCELLED, '' FROM observations
  UNION ALL SELECT 4, 'Issue Cancellation Rate', 100.0 * CANCELLED / NULLIF(ISSUES, 0), '%' FROM observations
  UNION ALL SELECT 5, 'Late Deliveries', BREACHES, '' FROM observations
  UNION ALL SELECT 6, 'GMV (IDR B)', GMV_IDR / 1e9, '' FROM observations
  UNION ALL SELECT 7, 'Orders Processed', ORDERS, '' FROM observations
  UNION ALL SELECT 8, 'Stock Sync Compliance', 100.0 * STOCK_SYNC_DONE / NULLIF(STOCK_SYNC_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Sellers Monitored', SELLER_COUNT, '' FROM book
  UNION ALL SELECT 10, 'Compliance Document Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Compliance Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                WHEN metrics.SORT_ORDER = 1 THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 2), '990.00'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.ISSUE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
