-- Order-cancellation risk scoring and order-issue forecast over the synthetic snapshot.
-- Predicts P(cancelled order for the seller in the next 7 days) per seller and
-- reports out-of-time holdout metrics; nothing is seeded as a prediction.
USE DATABASE IDENTIFIER($DEMO_DB);
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE VIEW ML.CANCEL_FEATURES AS
SELECT r.ENTITY_ID, r.EVENT_DATE, a.CATEGORY, a.RISK_TIER, a.SELLER_AGE_YEARS,
       r.RETURN_RATE_PCT, r.AVG_DISPATCH_HRS,
       AVG(r.RETURN_RATE_PCT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS RETURN_RATE_7D,
       SUM(r.CANCELLED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS CANCELLED_30D,
       IFF(SUM(r.CANCELLED_COUNT) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) > 0,
           'CANCEL', 'OK') AS LABEL,
       COUNT(*) OVER (PARTITION BY r.ENTITY_ID ORDER BY r.EVENT_DATE ROWS BETWEEN 1 FOLLOWING AND 7 FOLLOWING) AS FUTURE_DAYS
FROM RAW.SELLER_DAILY r JOIN RAW.SELLERS a ON a.ID = r.ENTITY_ID
-- City-wide courier disruptions are not seller-driven, so they are excluded from training.
WHERE r.ISSUE_TYPE <> 'Courier network disruption';

-- Time-based split: train on older labelled days, hold out the most recent 14 labelled days.
CREATE VIEW ML.CANCEL_TRAIN AS
SELECT CATEGORY, RISK_TIER, SELLER_AGE_YEARS, RETURN_RATE_PCT, AVG_DISPATCH_HRS, RETURN_RATE_7D, CANCELLED_30D, LABEL
FROM ML.CANCEL_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE < DATEADD('day', -21, CURRENT_DATE());

CREATE VIEW ML.CANCEL_HOLDOUT AS
SELECT ENTITY_ID, EVENT_DATE, CATEGORY, RISK_TIER, SELLER_AGE_YEARS, RETURN_RATE_PCT, AVG_DISPATCH_HRS, RETURN_RATE_7D, CANCELLED_30D, LABEL
FROM ML.CANCEL_FEATURES
WHERE FUTURE_DAYS = 7 AND EVENT_DATE >= DATEADD('day', -21, CURRENT_DATE());

CREATE SNOWFLAKE.ML.CLASSIFICATION ML.CANCEL_RISK_MODEL(
  INPUT_DATA => TABLE(ML.CANCEL_TRAIN),
  TARGET_COLNAME => 'LABEL'
);

-- Out-of-time holdout: precision/recall at 0.5 versus the base rate.
CREATE TABLE ML.CANCEL_RISK_HOLDOUT_METRICS AS
WITH scored AS (
  SELECT LABEL, ML.CANCEL_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'SELLER_AGE_YEARS', SELLER_AGE_YEARS,
           'RETURN_RATE_PCT', RETURN_RATE_PCT, 'AVG_DISPATCH_HRS', AVG_DISPATCH_HRS,
           'RETURN_RATE_7D', RETURN_RATE_7D, 'CANCELLED_30D', CANCELLED_30D)):probability:CANCEL::FLOAT AS P
  FROM ML.CANCEL_HOLDOUT
)
SELECT COUNT(*) AS N,
       AVG(IFF(LABEL = 'CANCEL', 1, 0)) AS BASE_RATE,
       SUM(IFF(P >= 0.5 AND LABEL = 'CANCEL', 1, 0)) / NULLIF(SUM(IFF(P >= 0.5, 1, 0)), 0) AS PRECISION_AT_50,
       SUM(IFF(P >= 0.5 AND LABEL = 'CANCEL', 1, 0)) / NULLIF(SUM(IFF(LABEL = 'CANCEL', 1, 0)), 0) AS RECALL_AT_50,
       CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM scored;

-- Latest-day score per seller (label unknown, so excluded from features).
CREATE TABLE ML.CANCEL_RISK_SCORES AS
WITH latest AS (
  SELECT * FROM ML.CANCEL_FEATURES
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY EVENT_DATE DESC) = 1
), scored AS (
  SELECT ENTITY_ID, EVENT_DATE,
         ML.CANCEL_RISK_MODEL!PREDICT(INPUT_DATA => OBJECT_CONSTRUCT(
           'CATEGORY', CATEGORY, 'RISK_TIER', RISK_TIER, 'SELLER_AGE_YEARS', SELLER_AGE_YEARS,
           'RETURN_RATE_PCT', RETURN_RATE_PCT, 'AVG_DISPATCH_HRS', AVG_DISPATCH_HRS,
           'RETURN_RATE_7D', RETURN_RATE_7D, 'CANCELLED_30D', CANCELLED_30D)) AS P
  FROM latest
)
SELECT ENTITY_ID, EVENT_DATE AS SCORED_AS_OF,
       ROUND(P:probability:CANCEL::FLOAT, 4) AS CANCEL_PROB_7D,
       CASE WHEN P:probability:CANCEL::FLOAT >= 0.5 THEN 'High'
            WHEN P:probability:CANCEL::FLOAT >= 0.25 THEN 'Medium' ELSE 'Low' END AS RISK_BAND,
       CURRENT_TIMESTAMP() AS SCORED_AT
FROM scored;

-- Marketplace-wide order-issue forecast (14 days) from the daily series, for support staffing.
CREATE VIEW ML.DAILY_ISSUES AS
SELECT EVENT_DATE::TIMESTAMP_NTZ AS TS, SUM(ISSUE_COUNT)::FLOAT AS ISSUE_COUNT
FROM RAW.SELLER_DAILY GROUP BY EVENT_DATE;

CREATE SNOWFLAKE.ML.FORECAST ML.ISSUE_FORECAST_MODEL(
  INPUT_DATA => TABLE(ML.DAILY_ISSUES),
  TIMESTAMP_COLNAME => 'TS',
  TARGET_COLNAME => 'ISSUE_COUNT'
);

CREATE TABLE ML.ISSUE_FORECAST AS
SELECT TS::DATE AS FORECAST_DATE, GREATEST(0, FORECAST) AS ISSUE_COUNT,
       GREATEST(0, LOWER_BOUND) AS LOWER_BOUND, UPPER_BOUND
FROM TABLE(ML.ISSUE_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));
