-- ============================================================================
-- 99_RESET.SQL — Reset E-Commerce Marketplace Analytics to clean demo state
-- ============================================================================
USE DATABASE ECOMMERCE_ANALYTICS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_GMV SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_SELLERS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_GMV SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.GMV_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.SELLER_HEALTH_SCORE REFRESH;
ALTER DYNAMIC TABLE CURATED.DEMAND_SIGNALS REFRESH;
ALTER DYNAMIC TABLE CURATED.CAMPAIGN_ROI REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ECOMMERCE_ANALYTICS.RAW.ORDERS → 50000000
-- SELECT COUNT(*) FROM ECOMMERCE_ANALYTICS.RAW.SELLERS → 500000
-- SELECT COUNT(*) FROM ECOMMERCE_ANALYTICS.RAW.BUYERS → 10000000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_GMV RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_SELLERS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_GMV RESUME;
